"""Which udev rule file is in force, and is it this version's? (#201)

Two defects fed each other.  ``check_permissions`` and the permission hint
looked only in ``/etc``, so every deb and Arch user -- whose package installs
the rule in ``/lib`` or ``/usr/lib`` -- was told on each failed connect that
rules were missing, while ``trcc doctor`` said OK.  Following that advice ran
``trcc system setup``, which wrote an ``/etc`` copy of the same name; udev
then skips the packaged one ("Skipping overridden file", measured in #201),
so every later rule fix shipped by a package never reached that user.
"""
from __future__ import annotations

from pathlib import Path

import pytest

from trcc.adapters.system import _udev
from trcc.adapters.system.linux import LinuxOS

_NAME = _udev.RULES_PATH.name


@pytest.fixture
def dirs(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> tuple[Path, Path]:
    """/etc and /usr/lib stand-ins, in udev's priority order."""
    etc, lib = tmp_path / "etc", tmp_path / "lib"
    etc.mkdir()
    lib.mkdir()
    monkeypatch.setattr(_udev, "RULES_DIRS", (etc, lib))
    monkeypatch.setattr(_udev, "RULES_PATH", etc / _NAME)
    return etc, lib


def test_a_packaged_rule_is_installed_rules(dirs) -> None:
    """MUTATION CHECK: look in /etc only again -> the false warning returns."""
    _, lib = dirs
    (lib / _NAME).write_text(_udev.build_udev_rules(), encoding="utf-8")

    assert LinuxOS.check_permissions(None) == []        # type: ignore[arg-type]
    assert "not permissions" in LinuxOS.permission_denied_hint(None)  # type: ignore[arg-type]


def test_no_rules_anywhere_says_so_with_a_command_that_runs(dirs) -> None:
    warnings = LinuxOS.check_permissions(None)          # type: ignore[arg-type]

    assert len(warnings) == 1
    assert "`trcc system setup`" in warnings[0]
    assert "python -m" not in warnings[0]


def test_an_old_etc_copy_hiding_the_packaged_rule_is_reported(dirs) -> None:
    from trcc.adapters.diagnostics.health import check_udev_rules_linux

    etc, lib = dirs
    (lib / _NAME).write_text(_udev.build_udev_rules(), encoding="utf-8")
    (etc / _NAME).write_text("# Thermalright TRCC devices — generated by "
                             "`trcc system setup`\n# an older rule set\n",
                             encoding="utf-8")

    state = _udev.rules_state()
    result = check_udev_rules_linux()

    assert (state.path, state.current, state.shadowed) == (etc / _NAME, False,
                                                          (lib / _NAME,))
    assert result.severity == "WARN"
    assert str(etc / _NAME) in result.message
    assert f"rm {etc / _NAME}" in (result.fix_hint or "")


def test_setup_leaves_a_current_packaged_rule_in_force(
    dirs, monkeypatch: pytest.MonkeyPatch,
) -> None:
    """It wrote /etc unconditionally, hiding the package's rule for good.
    MUTATION CHECK: write /etc regardless -> fails."""
    etc, lib = dirs
    (lib / _NAME).write_text(_udev.build_udev_rules(), encoding="utf-8")
    (etc / _NAME).write_text("# Thermalright TRCC devices — generated by "
                             "`trcc system setup`\n# older\n", encoding="utf-8")
    written: list[Path] = []
    monkeypatch.setattr(_udev.os, "geteuid", lambda: 0)
    monkeypatch.setattr(_udev, "_write_atomic", lambda path, content: written.append(path))
    monkeypatch.setattr(_udev.subprocess, "run", lambda *a, **k: None)
    monkeypatch.setattr(_udev, "_reload_udev", lambda: 0)

    assert _udev.install() == 0

    assert etc / _NAME not in written
    assert not (etc / _NAME).exists(), "our stale /etc copy still hides it"


def test_setup_never_removes_an_admins_own_rule_file(
    dirs, monkeypatch: pytest.MonkeyPatch,
) -> None:
    etc, lib = dirs
    (lib / _NAME).write_text(_udev.build_udev_rules(), encoding="utf-8")
    (etc / _NAME).write_text("# written by hand\n", encoding="utf-8")
    monkeypatch.setattr(_udev.os, "geteuid", lambda: 0)
    monkeypatch.setattr(_udev, "_write_atomic", lambda path, content: None)
    monkeypatch.setattr(_udev.subprocess, "run", lambda *a, **k: None)
    monkeypatch.setattr(_udev, "_reload_udev", lambda: 0)

    _udev.install()

    assert (etc / _NAME).read_text(encoding="utf-8") == "# written by hand\n"
